# Generated by Django 6.1.1 on 2026-09-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('risk_default', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('IMMEDIATE', 'Immediate')], default='LOW', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('CONSTITUTION', 'Constitution'), ('LEGISLATION', 'Legislation'), ('POLICY', 'Policy'), ('REGULATION', 'Regulation'), ('GOVERNMENT_GUIDANCE', 'Government Guidance'), ('JUDICIAL_DECISION', 'Judicial Decision'), ('INSTITUTIONAL_GUIDANCE', 'Institutional Guidance')], max_length=30)),
                ('publisher', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(default='Kenya', max_length=100)),
                ('url', models.URLField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('last_verified', models.DateField()),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('REVIEW_REQUIRED', 'Review Required'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='VERIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Source',
                'verbose_name_plural': 'Legal Sources',
                'ordering': ['jurisdiction', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('default_risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('IMMEDIATE', 'Immediate')], default='LOW', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='core.journey')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['journey', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RightsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_code', models.CharField(max_length=50, unique=True)),
                ('jurisdiction', models.CharField(default='Kenya', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('plain_language_summary', models.TextField()),
                ('legal_reference', models.CharField(max_length=255)),
                ('section_reference', models.CharField(blank=True, max_length=150)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('IMMEDIATE', 'Immediate')], default='LOW', max_length=10)),
                ('next_step_text', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('last_verified', models.DateField()),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('REVIEW_REQUIRED', 'Review Required'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='VERIFIED', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rights_records', to='core.journey')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rights_records', to='core.legalsource')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rights_records', to='core.topic')),
            ],
            options={
                'verbose_name': 'Rights Record',
                'verbose_name_plural': 'Rights Records',
                'ordering': ['journey', 'topic', 'record_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('journey', 'slug'), name='unique_topic_slug_per_journey'),
        ),
    ]
