# Generated by Django 6.1.1 on 2026-09-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('ABUSE', 'Abuse'), ('IMMEDIATE_DANGER', 'Immediate Danger'), ('LAW_ENFORCEMENT', 'Law Enforcement')], max_length=25)),
                ('pattern', models.TextField(help_text='Comma-separated keywords or phrases. A message matches this rule if it contains any of these terms (case-insensitive).')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('IMMEDIATE', 'Immediate')], default='LOW', max_length=10)),
                ('action', models.CharField(choices=[('NORMAL_FLOW', 'Normal Flow'), ('SHOW_SUPPORT', 'Show Support'), ('SHOW_HIGH_RISK_SUPPORT', 'Show High Risk Support'), ('SHOW_IMMEDIATE_SAFETY', 'Show Immediate Safety')], default='NORMAL_FLOW', max_length=30)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = evaluated first. Use to control rule precedence.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Rule',
                'verbose_name_plural': 'Risk Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('service_type', models.CharField(choices=[('CHILD_PROTECTION', 'Child Protection'), ('GBV_SUPPORT', 'GBV Support'), ('LEGAL_AID', 'Legal Aid'), ('POLICE_OVERSIGHT', 'Police Oversight'), ('HEALTH_SUPPORT', 'Health Support'), ('GENERAL_SUPPORT', 'General Support')], max_length=30)),
                ('description', models.TextField()),
                ('jurisdiction', models.CharField(default='Kenya', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('available_24_7', models.BooleanField(default=False)),
                ('source_url', models.URLField(help_text='URL of the official or published source confirming this service.')),
                ('last_verified', models.DateField()),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('REVIEW_REQUIRED', 'Review Required'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='VERIFIED', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Service',
                'verbose_name_plural': 'Support Services',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('step_number', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('action_type', models.CharField(choices=[('RIGHTS_GUIDANCE', 'Rights Guidance'), ('SUPPORT_REFERRAL', 'Support Referral'), ('LEGAL_ASSISTANCE', 'Legal Assistance'), ('REPORTING_OPTION', 'Reporting Option'), ('SAFETY_ACTION', 'Safety Action')], max_length=25)),
                ('last_verified', models.DateField()),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('REVIEW_REQUIRED', 'Review Required'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='VERIFIED', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, help_text='Legal basis for this action step, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_paths', to='core.legalsource')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_paths', to='core.topic')),
                ('support_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_paths', to='core.supportservice')),
            ],
            options={
                'verbose_name': 'Action Path',
                'verbose_name_plural': 'Action Paths',
                'ordering': ['topic', 'step_number'],
                'constraints': [models.UniqueConstraint(fields=('topic', 'step_number'), name='unique_step_number_per_topic')],
            },
        ),
    ]
